### ISSUE TITLE
Support has ended streak recovery via form

### ISSUE THREAD

**Issue by 0dm** [cocomo29/SnapStreak-Recovery#2]
The form is still accessible if you avoid the redirect, but recaptcha is broken so it doesn't work. 

Do you think we can get around this by sending POST requests?

**Comment by cocomo29** [comment]
Hey 0dm,

I don't think so, even if it is possible to do so right now, it will be patched real soon.

Ty for dropping this amazing suggestion tho, but I think this repo will be gone for good now.
